apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        aadpodidbinding: catalog
    spec:
      containers:
        - name: catalog
          image: playeconomy26.azurecr.io/play.catalog:1.0.4
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: playeconomy26
            - name: ServiceSettings__Authority
              value: https://playeconomy26.eastus.cloudapp.azure.com/identity-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5143
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5143
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5143
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - port: 81
      targetPort: 5143
