apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: identity-mapping
spec:
  hostname: playeconomy26.eastus.cloudapp.azure.com
  prefix: /identity-svc/
  service: identity-service.identity
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: catalog-mapping
spec:
  hostname: playeconomy26.eastus.cloudapp.azure.com
  prefix: /catalog-svc/
  service: catalog-service.catalog
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: seq-mapping
spec:
  hostname: playeconomy.eastus.cloudapp.azure.com
  prefix: /seq/
  service: seq.observability
